### ISSUE TITLE
Unusable on Firefox Nightly for Android

### ISSUE THREAD

**Issue by ghost** [chenzhekl/unblock-youku-firefox#1]
I am using the latest version of Firefox Nightly for Android.

**What works**
Installation of this add-on

**What does not**
Context menu shows `Unblock Youku is.aq for solutions.`.
The options page pops out after clicking the aforementioned context menu entry. However, the mode cannot be chosen. Clicking any of the buttons has no effect.
As a result, the "unblock" effect **cannot** be achieved.

Related:
[addon/manifest.json](https://github.com/chenzhekl/unblock-youku-firefox/blob/d15fe2681e50ef52ed14cc37a551556d62672647/addon/manifest.json):
```
    "browser_action": {
        "default_title": "Unblock Youku isn't working properly! Visit http://uku.im/faq for solutions.",
        "default_icon": "icons/icon19gray.png",
        "default_popup": "popup/index.html"
    },
```

Screenshots:
![contextmenu](https://user-images.githubusercontent.com/32787247/31572745-2b2769cc-b09c-11e7-9e49-aefadb67fd05.png)
![options](https://user-images.githubusercontent.com/32787247/31572746-316f0088-b09c-11e7-8e93-1485b9ad465c.png)

**Comment by chenzhekl** [comment]
Um... It should have worked. I will give it a look tonight.

**Comment by chenzhekl** [comment]
I uploaded a new version to AMO, and now it should work. If the problem is still around, feel free to reopen this issue.

Thanks for your feedback! @8tx81vb8rt8ci4whgk
