### ISSUE TITLE
Update URLs Please

### ISSUE THREAD

**Issue by placetne** [chenzhekl/unblock-youku-firefox#10]
Could you update the URLs from the chrome version of Unblock Youku?

https://github.com/uku/Unblock-Youku/blob/master/shared/urls.js
 
Some of the sites have stopped working on this version for Firefox, but it works on Chrome because of the new URLs. Thanks.

**Comment by chenzhekl** [comment]
Quite sorry for that. Updating the URL database has been on my to-do list
for a long time, but I cannot find a time to do it. Hopefully It can be
done after tomorrow's meeting.

**Comment by chenzhekl** [comment]
Fixed in 13433930605438f1fee924b83afccafc8b689a9d.
