### ISSUE TITLE
Can't log in to v.qq.com with lite and full mode

### ISSUE THREAD

**Issue by yluvs** [chenzhekl/unblock-youku-firefox#12]
Firefox version: 66.0.2
Unblock Youku version: 0.3.5

Hello,
I haven't been able to sign in to tencent video (http://v.qq.com) with lite and full mode for a few months. After logging in, I just get signed out almost immediately. I haven't had this issue with Chrome or Waterfox though. Could you please look into this problem? Thank you.

**Comment by chenzhekl** [comment]
Hi, yluvs,

Thanks for reporting the issue, I will look into it tonight.

**Comment by chenzhekl** [comment]
This has been fixed in 8a50d1c85cc00dd8c197207fdfc51c9b574cb809. If you are still having issues, please feel free to reopen it.
