### ISSUE TITLE
Firefox not supporting this starting firefox 57

### ISSUE THREAD

**Issue by JonathanZhang911** [chenzhekl/unblock-youku-firefox#13]

**Comment by chenzhekl** [comment]
Hi, Jonathan,

Probably you encountered  the issue of Firefox. Can you upgrade to the latest version to see if it's fixed?

https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

https://news.ycombinator.com/item?id=19834432

Best,
Zhe
________________________________
发件人: JonathanZhang911 <notifications@github.com>
发送时间: 星期一, 五月 6, 2019 08:19
收件人: chenzhekl/unblock-youku-firefox
抄送: Subscribed
主题: [chenzhekl/unblock-youku-firefox] Firefox not supporting this starting firefox 57 (#13)


―

**Comment by chenzhekl** [comment]
Good know it works for you. :)
