### ISSUE TITLE
can not play bilibili videos with unblock youku on. They might updated something recently

### ISSUE THREAD

**Issue by JonathanZhang911** [chenzhekl/unblock-youku-firefox#15]

**Comment by chenzhekl** [comment]
Thanks for reporting! It's an upstream problem and I can confirm it. Unfortunately, our best bet for now is waiting for them to fix it. Before that, It's recommended to turn off this add-on while visiting Bilibili.com.

**Comment by chenzhekl** [comment]
It seems that Bilibili is working properly now. If you are still experiencing the problem, please feel free to reopen it.
