### ISSUE TITLE
Warning: Potential Security Risk Ahead

### ISSUE THREAD

**Issue by txin** [chenzhekl/unblock-youku-firefox#19]
The extension is switched to the 'full' mode.
Received following message:
"Firefox detected a potential security threat and did not continue to www.bilibili.com. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details."

Received no response even after clicking 'Accept the risk and continue' .

**Comment by chenzhekl** [comment]
Hi, txin. Thanks for reporting. Please can you provide the Firefox version and the URL that caused the problem?

**Comment by txin** [comment]
Hello, thanks for reaching out.
Seems that the problem has been resolved.
Not sure whether this is a server side problem though, or my network's problem.
Thank you anyway!
