### ISSUE TITLE
No Newline at End of File

### ISSUE THREAD

**Issue by ghost** [chenzhekl/unblock-youku-firefox#3]
Some files in this repository does not have a newline character at end of file. [This may lead to unexpected behavior when using tools that work on the file](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file).

**Comment by chenzhekl** [comment]
Frankly speaking, there are more style problems than missing newlines, e.g. the `common/black_hole.js` is a direct port of the chrome extension and violates style rules for this project for every line. I am considering to clean up the code once I have time. It would be appreciated if you could help (e.g. send a PR).
