### ISSUE TITLE
unblock-youku-firefox cannot auto-run in Firefox

### ISSUE THREAD

**Issue by s174436** [chenzhekl/unblock-youku-firefox#7]
The unblock-youku-firefox (version 0.1.4) cannot run automatically when Firefox (version 57.0 32-bit) is started up. When Firefox is started up each time, it is in "OFF" mode and I need to turn on it manually by either choosing "LITE" or "FULL" mode. The operating system I use is Windows 7 Ultimate.

**Comment by chenzhekl** [comment]
Setting it to "FULL" mode by default may not be expected for every user. How about remembering the last choice across Firefox restarts?

**Comment by s174436** [comment]
It cannot remember the last choice across Firefox restarts. When I choose either "LITE" or "FULL" mode as the last choice, it switches to "OFF" mode when Firefox restarts.

**Comment by chenzhekl** [comment]
Fixed in 991f90fd76bc0dce4f9099a11b974c431f015d90.
